

const books = [{
    "id" : 'CF0001',
    "name" : "1984",
    "review" : "En 1984, Londres está controlada por un gobieno totalitario. El Gran Hermano lo vigila absolutamente todo. La mano ejecutora, la Policía del Pensamiento, controla cada aspecto de la vida de los ciudadanos. Un hombre llamado Winston Smith, trabajador del Ministerio de la Verdad, intentará rebelarse contra el régimen opresor..",
    "img" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCjgIkmqNgIc1hZTa-QHt44TC22adESl8ZvQ&usqp=CAU",
    "price" : 350,
    "stock": 12,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "George Orwell",
    "top": true,
    "offers":false,
    "news":false,
  },{
    "id" : 'PO0001',
    "name" : "Estudio en Escarlata",
    "review" : "Poco podía imaginar el Dr. John Watson que compartir piso en Londres iba a ser más emocionante y arriesgado que combatir en Afganistán. ¿El responsable? Su compañero de piso, Sherlock Holmes, cuyas dotes deductivas y personalidad fascinan a Watson.Estudio en escarlata es el trepidante comienzo de la andadura en común de los célebres inquilinos del 221B de Baker Street.",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/718BaebCGhL.jpg",
    "price" : 400,
    "stock": 5,
    "genre": "Policial",
    "available" : true,
    "writer" : "Edgar Allan Poe",
    "top": false,
    "offers":true,
    "news":false,
    
  },
  { "id" : 'FA0001',
    "name" : "Harry Potter y La Orden del Fenix",
    "review" : " El Ministerio de Magia niega que Voldemort haya regresado y ha iniciado una campaña de desprestigio contra Harry y Dumbledore, para lo cual ha asignado a la horrible profesora Dolores Umbridge la tarea de vigilar todos sus movimientos. Así pues, además de sentirse solo e incomprendido, Harry sospecha que Voldemort puede adivinar sus pensamientos, e intuye que el temible mago trata de apoderarse de un objeto secreto que le permitiría recuperar su poder destructivo..",
    "img" : "https://catalogue.immateriel.fr/resources/2f/16/1c0e31e4be76f8dfbbba5cb6905f78b92bb0226e1dc51affd18947e3e185.jpg",
    "price" : 800,
    "stock": 0,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "J.K. Rowling",
    "top": false,
    "offers":true,
    "news":false,
  },
  { "id" : 'HI0001',
    "name" : "Las venas abiertas de America Latina",
    "review" : "Las venas abiertas de América Latina” es un libro escrito por Eduardo Galeano. Aquí nos revela la realidad histórica de nuestra América, y nos proporciona una perspectiva acerca del contexto político específicamente de América, donde el lector puede hacer comparaciones pertinentes con respecto a la cultura de Estados Unidos y la de América Latina.",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/41E6BToW6CL._SX319_BO1,204,203,200_.jpg",
    "price" : 950,
    "stock": 4,
    "genre": "Historia",
    "available" : true,
    "writer" : "Eduardo Galeano",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'FA0002',
    "name" : "Harry potter y la camara secreta",
    "review" : "Mientras Harry espera impaciente en casa de sus insoportables tíos el inicio del segundo curso del Colegio Hogwarts de Magia y Hechicería, un elfo aparece en su habitación y le advierte de que una amenaza mortal se cierne sobre la escuela. Harry no se lo piensa dos veces y, acompañado de Ron, se dirige a Hogwarts en un coche volador. Pero, ¿puede un aprendiz de mago defender la escuela de los malvados que pretenden destruirla? Sin saber que alguien ha abierto la Cámara de los Secretos, dejando escapar una serie de monstruos peligrosos, Harry y sus amigos Ron y Hermione tendrán que enfrentarse con arañas gigantes, serpientes encantadas, fantasmas enfurecidos y, sobre todo, con la mismísima reencarnación de su más temible adversario.",
    "img" : "https://contentv2.tap-commerce.com/cover/large/9789878000114_1.jpg?id_com=1113",
    "price" : 1500,
    "stock": 0,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "Edgar Allan Poe",
    "top": false,
    "offers":true,
    "news":false,
    
  },
  { "id" : 'PO0002',
    "name" : "El cuarto mono",
    "review" : "El detective de la policía de Chicago Sam Porter investiga el caso de un hombre atropellado, pues los indicios en la escena del crimen apuntan a que se trata de El Cuarto Mono, un asesino en serie que ha estado aterrorizando la ciudad. Su modus operandi consistía en enviar tres cajas blancas a los padres de las víctimas que secuestra y mata: una primera con una oreja, una segunda con los dos ojos, y otra con la lengua; y finalmente dejar abandonado el cuerpo sin vida en algún lugar.El hombre atropellado llevaba una de esas cajas blancas. Se inicia así una frenética carrera contrarreloj para averiguar dónde se encuentra encerrada la próxima víctima.",
    "img" : "https://planetadelibrosar5.cdnstatics.com/usuaris/libros/fotos/304/m_prensa/303713_el-cuarto-mono_9788423353941_3d.png",
    "price" : 1200,
    "stock": 7,
    "genre": "Policial",
    "available" : true,
    "writer" : "J.D Barker",
    "top": false,
    "offers":false,
    "news":false,
    
  },
  { "id" : 'CF0002',
    "name" : "Fahrenheit 451",
    "review" : "Fahrenheit 451' no es un libro fácil de leer, porque nos lleva a una situación que no tiene nada de fantástica. Estamos en un país donde no se puede leer. De hecho, el trabajo del bombero Montag, el protagonista, no es apagar incendios, sino provocarlos. Se dedica a quemar libros para evitar que la población piense y se la pueda manipular;",
    "img" : "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/elle-fahrenheit451-1582115505.jpg?crop=1xw:1xh;center,top&resize=480:*",
    "price" : 850,
    "stock": 16,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "Ray Bradbury",
    "top": false,
    "offers":false,
    "news":false,
    
  },
  { "id" : 'CF0003',
    "name" : "El señor de las moscas",
    "review" : "Una obra cuya calidad tiene tanto defensores como detractores, y que fue adaptada recientemente como serie por Netflix bajo el título 'The Society'. William Golding, premio Nobel de Literatura en 1983 nos lleva hasta la próxima guerra mundial, cuando el avión en el que viajan un grupo de jóvenes se estrella en una isla desconocida. Sin adultos que les supervisen, todo comienza siendo una fiesta, porque pueden hacer lo que quieran. Con lo que no contaban es con la dificultad y la tragedia de establecer una sociedad..",
    "img" : "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/elle-elsen-ordelasmoscas-1582115504.jpg?crop=1xw:1xh;center,top&resize=480:*",
    "price" : 1400,
    "stock": 2,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "William Golding",
    "top": false,
    "offers":true,
    "news":false,
  },
  { "id" : 'CF0004',
    "name" : "El cuento de la criada",
    "review" : "La serie de HBO inspirada en él ha dado alas a este cuento escrito a mediados de los 90 por Margaret Atwood, una historia inquietante, oscura y angustiosa que nos sitúa en la república de Gilead, donde Defred es una más de tantas mujeres que han perdido todos sus derechos y que solo sirven para una cosa: procrear. Atwood nos sumerge en un mundo asfixiante que nos hace reflexionar si podría ser nuestro propio planeta.",
    "img" : "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cuentocriada-1524221026.jpg?crop=1xw:1xh;center,top&resize=480:*",
    "price" : 1700,
    "stock": 0,
    "genre": "Ciencia Ficcion",
    "available" : false,
    "writer" : "Margaret Atwood",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'DR0001',
    "name" : "La buena suerte",
    "review" : "Rosa Montero regresa para conquistar nuevamente al lector con una novela que captura y engancha a través de Pablo, de Raluca, de todos los vecinos de Pozonegro que guardan un secreto. A través de Pablo viviremos con él la caída y las consecuencias de un terremoto emocional, el suyo propio, pero también cómo uno puede enfrentarse al mismo y descubrirse, redescubrirse y ver hacia dónde puede llevarle.",
    "img" : "https://espaciolibros.com//wp-content/uploads/2020/08/libros-recomendados-2020-rosa-montero-la-buena-suerte.jpg",
    "price" : 700,
    "stock": 10,
    "genre": "Drama",
    "available" : true,
    "writer" : "Rosa Montero",
    "top": false,
    "offers":true,
    "news":false,
  },
  { "id" : 'DR0002',
    "name" : "Cien años de soledad",
    "review" : "«Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.» Con estas palabras empieza una novela legendaria, una de las aventuras literarias más fascinantes del siglo XX. La familia Buendía-Iguarán, con sus milagros, fantasías, obsesiones, tragedias, incestos, adulterios, rebeldías, descubrimientos y condenas, representa al mismo tiempo el mito y la historia, la tragedia y el amor del mundo entero. «El Quijote de nuestro tiempo.» Pablo Neruda",
    "img" : "https://2.bp.blogspot.com/-BbVKIZIg2pA/UO5o9vqB7TI/AAAAAAAAACE/OPrwTtiHfAs/s1600/cienanos.gif",
    "price" : 700,
    "stock": 10,
    "genre": "Drama",
    "available" : true,
    "writer" : "Gabriel Garcia Marquez",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'FA0003',
    "name" : "El señor de los anillos",
    "review" : "El Señor de los Anillos es una obra ambientada en la Tercera Edad de La Tierra Media, mundo inventado por JRR Tolkien. Narra una gran aventura: el viaje emprendido por 9 compañeros para destruir un Anillo lleno de poder maléfico. Su argumento es complejo y se narra con la participación de varios protagonistas que se mueven en varios hilos narrativos. Es una obra coral en la que destacan unos pocos protagonistas (Frodo, Sam, Gandalf y Aragorn).",
    "img" : "https://2.bp.blogspot.com/_x2vBZUXDzVk/S-RhI8ugR-I/AAAAAAAAAls/8dTO6VD_2rM/s1600/imagen_biblioesdla_1.jpg",
    "price" : 3700,
    "stock": 10,
    "genre": "Fantastico",
    "available" : true,
    "writer" : "J.R.R Tolkien",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'CF0005',
    "name" : "Un mundo feliz",
    "review" : "Un mundo feliz es un clásico de la literatura de este siglo. Con ironía mordiente, el genial autor inglés plasma una sombría metáfora sobre el futuro, muchas de cuyas previsiones se han materializado, acelerada e inquietantemente, en los últimos años. La novela describe un mundo en el que finalmente se han cumplido los peor es vaticinios: triunfan los dioses del consumo y la comodidad, y el orbe se organiza en diez zonas en apariencia seguras y estables. Sin embargo, este mundo ha sacrificado valores humanos esenciales, y sus habitantes son procreados in vitro a imagen y semejanza de una cadena de montaje…",
    "img" : "https://i.pinimg.com/originals/01/db/f0/01dbf0de11087b535d2c660481dd4135.jpg",
    "price" : 1200,
    "stock": 8,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "Aldous Huxley",
    "top": true,
    "offers":false,
    "news":false,
  },
  { "id" : 'HI0002',
    "name" : "Manuel Belgrano:El hombre del Bicentenario",
    "review" : "En esta nueva obra, Felipe Pigna aborda el estudio integral de la agitada vida de Belgrano, tanto en lo público como en lo privado y familiar. Además de sus facetas más conocidas como protagonista de la Revolución de Mayo y general de la Independencia, aparecen con gran relevancia en estas páginas los aspectos menos divulgados: su ideario progresista y las incontables batallas que libró para llevarlo a la práctica.",
    "img" : "https://www.planetadelibros.com.ar/usuaris/libros/fotos/216/m_libros/portada_manuel-belgrano_felipe-pigna_201604261432.jpg",
    "price" : 2000,
    "stock": 12,
    "genre": "Historia",
    "available" : true,
    "writer" : "Felipe Pigna",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'HI0003',
    "name" : "Mujeres insolentes de la historia",
    "review" : "Hicieron historia. Igual que muchos hombres.Pero a ellas se les mezquinó la memoria de sus actos. Tardaron en aparecer en los libros, en las revistas, en los manuales de la escuela, en las conmemoraciones. Fueron mujeres valientes, arriesgadas, talentosas, capaces de ir contra lo que su época decía que había que hacer. Estuvieron a la altura de una historia que luego las arrumbó en un costado, fueron las “insolentes” en ese mundo.En este libro, Felipe Pigna nos cuenta la vida de algunas mujeres latinoamericanas que se sublevaron para hacer lo que querían.",
    "img" : "https://planetadelibrosar2.cdnstatics.com/usuaris/libros/fotos/272/m_libros/portada___201804092101.jpg",
    "price" : 1800,
    "stock": 8,
    "genre": "Historia",
    "available" : true,
    "writer" : "Felipe Pigna",
    "top": false,
    "offers":false,
    "news":true,
  },
  { "id" : 'PO0003',
    "name" : "El muñeco de nieve",
    "review" : "Las aventuras del policía noruego Harry Hole gozan hoy de un amplio público. Esta es una de las primeras novelas de Jo Nesbo, pero no nos equivocaríamos al valorarla como la más perfecta y contenida (en otras el protagonista cae en un desbarre más peliculero). En estas páginas Hole se enfrenta al caso de un psicópata que va haciendo desaparecer mujeres y dejando un muñequito de nieve con bufanda como señal… 'a priori'. Pero también trata otros asuntos como la paternidad. Una novela trepidante que fue llevada al cine, más mal que bien. No le hacía falta. Tiene fans por todo el planeta. Hasta Patti Smith, ávida lectora, ha declarado alimentarse con fruición de Nesbo.",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/916g3Dquw7L.jpg",
    "price" : 1400,
    "stock": 8,
    "genre": "Policial",
    "available" : true,
    "writer" : "Jo Nesbo",
    "top": true,
    "offers":false,
    "news":false,
  },
  { "id" : 'PO0004',
    "name" : "Crimen y castigo",
    "review" : "Crimen y castigo, una novela de asesinato y angustia, en la que una de las características más determinantes es la profundización de la psicología de los personajes. Esta dedicación a la descripción y los diálogos internos acerca la novela a un ensayo sobre la psicología humana.",
    "img" : "https://cdn-0.infolibros.org/wp-content/uploads/2020/06/11-Crimen-y-castigo-Fiódor-Dostoievski.jpg?ezimgfmt=rs:292x456/rscb32/ng:webp/ngcb32",
    "price" : 3400,
    "stock": 11,
    "genre": "Policial",
    "available" : true,
    "writer" : "Fiódor Dostoievski",
    "top": false,
    "offers":false,
    "news":true,
  },
  { "id" : 'HI0004',
    "name" : "Don Quijote de la Mancha",
    "review" : "Crimen y castigo, una novela de asesinato y angustia, en la que una de las características más determinantes es la profundización de la psicología de los personajes. Esta dedicación a la descripción y los diálogos internos acerca la novela a un ensayo sobre la psicología humana.",
    "img" : "https://cdn-0.infolibros.org/wp-content/uploads/2020/06/18-Don-Quijote-de-la-Mancha-Miguel-de-Cervantes.png?ezimgfmt=rs:0x0/rscb32/ng:webp/ngcb32",
    "price" : 2500,
    "stock": 2,
    "genre": "Historia",
    "available" : true,
    "writer" : "Miguel de Cervantes",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'FA0004',
    "name" : "Moby Dick",
    "review" : "Crimen y castigo, una novela de asesinato y angustia, en la que una de las características más determinantes es la profundización de la psicología de los personajes. Esta dedicación a la descripción y los diálogos internos acerca la novela a un ensayo sobre la psicología humana.",
    "img" : "https://cdn-0.infolibros.org/wp-content/uploads/2020/06/76-Moby-Dick-Herman-Melville.jpg?ezimgfmt=rs:0x0/rscb32/ng:webp/ngcb32",
    "price" : 2500,
    "stock": 0,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "Herman Melville",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'PO0005',
    "name" : "Cianuro Espumoso",
    "review" : "En el reservado de un selecto restaurante, seis personas se reúnen alrededor de una mesa preparada para siete comensales. Ante el asiento vacío hay un ramillete de romero en memoria de Rosemary Burton, fallecida en aquel mismo escenario un año atrés después de haber ingerido cianuro disuelto en su copa. En aquel momento todo el mundo pensó que se trataba de un suicidio. Hoy ya no. Ahora existen sospechas fundadas de que en realidad Rosemary fue asesinada. Y lo que en un principio parecía una cena organizada en homenaje a la difunta se va a convertir en otra cosa muy distinta. Una peligrosa conmemoración que puede volver a acabar en tragedia cuando, al alzar la copa para brindar en recuerdo de la fallecida, uno de los comensales se desploma en su silla.",
    "img" : "https://planetadelibrosar4.cdnstatics.com/usuaris/libros/fotos/204/m_libros/portada_cianuro-espumoso_agatha-christie_201506292037.jpg",
    "price" : 4500,
    "stock": 22,
    "genre": "Policial",
    "available" : false,
    "writer" : "Agatha Christie",
    "top": false,
    "offers":false,
    "news":true,
  },
  { "id" : 'FA0005',
    "name" : "Maze Runner",
    "review" : "Al despertar dentro de una oscura caja en movimiento, Thomas solo recuerda su nombre. No sabe quién es. Tampoco hacia dónde va. Pero no está solo: cuando el ascensor llega a su destino, las puertas se abren y se ve rodeado por un grupo de jóvenes (todos varones).El Glade (el Claro en España, el Área en Hispanoamérica) es un espacio abierto cercado por muros gigantescos llenos de vegetación. Al igual que Thomas, ninguno de ellos sabe cómo ha llegado allí. Ni por qué. De lo que están seguros es de que cada mañana las puertas de piedra que los separan del laberinto que los rodea se abren y por la noche, se cierran.",
    "img" : "https://upload.wikimedia.org/wikipedia/en/d/db/The_Maze_Runner_cover.png",
    "price" : 3000,
    "stock": 2,
    "genre": "Fantastico",
    "available" : true,
    "writer" : "James Dashner",
    "top": true,
    "offers":false,
    "news":false,
  },
  { "id" : 'FA0006',
    "name" : "Partials",
    "review" :"En 2076, en un mundo devastado por la guerra, los seres humanos están al borde de la extinción y la clave de la supervivencia está en manos de una chica de 16 años. La Humanidad está a punto de desaparecer tras haber perdido la guerra con los Parciales (seres creados con tecnología genética, idénticos a nosotros). Los humanos sobrevivientes fueron reducidos a unos pocos miles por el RM, un virus letal utilizado como arma biológica, al cual solo parte de la población es inmune. Los habitantes se concentraron en Long Island y, aunque los Parciales se han retirado misteriosamente, su amenaza persiste. Pero lo peor es que en once años no ha habido un solo bebé que haya sobrevivido al RM.",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/41Qeu6Z+IyL._SX343_BO1,204,203,200_.jpg",
    "price" : 1100,
    "stock": 16,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "Dan Wells",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'DR0003',
    "name" : "La piedra Lunar",
    "review" : "Un oficial inglés roba un precioso diamante de los ojos de una estatua hindú muy famosa, que trae consigo una maldición. Muchísimos años después, la piedra es heredada a la sobrina de este oficial por su cumpleaños y junto con ella, vienen tres hindús que buscan recuperarla.",
    "img" : "https://eslamoda.com/wp-content/uploads/sites/2/2017/04/la-piedra-lunar-libro-600x927.jpg",
    "price" : 3000,
    "stock": 0,
    "genre": "Drama",
    "available" : false,
    "writer" : "Wilkie Collins",
    "top": false,
    "offers":false,
    "news":true,
  },
  { "id" : 'DR0004',
    "name" : "Memorias de una geisha",
    "review" :"Se dice que no se debe juzgar a un libro por su película y aunque su película es buenísima, el libro se la lleva de calle. Sayuri es una chica dentro de un mundo donde las jóvenes son adiestradas en el arte de la seducción y donde las convencen que, para ellas, el amor no es más que un espejismo.",
    "img" : "https://eslamoda.com/wp-content/uploads/sites/2/2017/04/geisha-600x897.jpg",
    "price" : 4300,
    "stock": 2,
    "genre": "Drama",
    "available" : false,
    "writer" : "Arthur Golden",
    "top": true,
    "offers":false,
    "news":false,
  },
  { "id" : 'DR0005',
    "name" : "Buscando a Alaska",
    "review" : "Miles vive su vida sin emoción alguna, un día decide mudarse a Culver Creek, un internado fuera de lo común, donde disfrutará por primera vez de la libertad al conocer a Alaska Young, una chica preciosa, descarada, fascinante y autodestructiva, que de alguna manera arrastrará a Miles a su mundo.",
    "img" : "https://eslamoda.com/wp-content/uploads/sites/2/2017/04/buscando-a-alaska-600x940.jpg",
    "price" : 2200,
    "stock": 12,
    "genre": "Drama",
    "available" : true,
    "writer" : "John Green",
    "top": false,
    "offers":false,
    "news":true,
  },
  {  "id" : 'CF0006',
    "name" : "Beso Feroz",
    "review" : "El autor de ‘Gomorra’ vuelve a un mundo que conoce muy bien, pero esta vez desde una perspectiva de ficción. Con todo, los avatares de unos chavales que quieren iniciarse en la mafia napolitana se viven como muy reales.",
    "img" : "https://media.revistagq.com/photos/5e4f92ec60f10d0008cd205b/master/w_100%2cc_limit/beso.jpg",
    "price" : 4000,
    "stock": 8,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "Roberto Saviano",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0001',
    "name" : "El Resplandor",
    "review" : "Jack Torrance acepta una oferta de trabajo en un hotel de montaña que se encuentra a 65 kilómetros del pueblo más cercano. Además, las carreteras se encuentran cerradas al tráfico por las fuertes nevadas del invierno. Pronto comenzarán a manifestarse espíritus y apariciones extrañas. Es el propio hotel el que intenta controlar tanto a los vivos como a los muertos. Danny, el hijo de Jack tiene la capacidad de ver visiones sobre el pasado del hotel y de resistirse a su poder hipnótico. Es entonces cuando su padre comienza a enloquecer.",
    "img" : "https://www.antena3.com/newa3flash/modulos_blancos/uploader/uploads/El Resplandor - Stephen King.jpg",
    "price" : 4200,
    "stock": 1,
    "genre": "Terror",
    "available" : true,
    "writer" : "Stephen King",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0002',
    "name" : "El Visitante",
    "review" : "En la ciudad ficticia de Flint City, Oklahoma, el detective de la policía Ralph Anderson arresta al entrenador de béisbol y profesor Terry Maitland frente a una multitud de espectadores, acusándolo de violar, matar y mutilar a un niño de 11 años. La ciudad se vuelve rápidamente contra Maitland, quien insiste en que es inocente y contrata al anciano abogado Howie Gold para que lo ayude, pero Anderson tiene testigos oculares y pruebas físicas claras (ADN y huellas dactilares) de su culpabilidad. Mientras tanto, los ansiosos reporteros acosan a la esposa de Terry, Marcy, y a sus dos hijas, Sarah y Grace. Pronto se revelará que existe algo imposible de explicar en estos terribles eventos.",
    "img" : "https://static.megustaleer.com/images/libros_650_x/EL021206.jpg",
    "price" : 1800,
    "stock": 4,
    "genre": "Terror",
    "available" : true,
    "writer" : "Stephen King",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0003',
    "name" : "Cujo",
    "review" : "La historia se enfoca en la familia Trenton: Victor, un diseñador de publicidad, su esposa, Donna, y su hijo de cuatro años, Tad. Los últimos son aterrorizados por Cujo, un San Bernardo rabioso. El relato tiene lugar en la ciudad ficticia de Castle Rock, Maine, y se entremezcla con las vidas residentes de allí. No hay capítulos oficiales, sino que hay pasajes, que indican cuando el autor alterna a otro punto de vista. ",
    "img" : "http://quelibroleo.com/images/libros/9788497595186.jpg",
    "price" : 2200,
    "stock": 0,
    "genre": "Terror",
    "available" : false,
    "writer" : "Stephen King",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0004',
    "name" : "IT",
    "review" : "Cuenta la historia de un grupo de siete niños que son aterrorizados por un malvado monstruo -al que llaman «Eso»- que es capaz de cambiar de forma, alimentándose del terror que produce en sus víctimas.",
    "img" : "https://loresumo.com/wp-content/uploads/2019/08/It-el-libro-6.jpg",
    "price" : 2200,
    "stock": 12,
    "genre": "Terror",
    "available" : true,
    "writer" : "Stephen King",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0005',
    "name" : "El Terror",
    "review" : "En septiembre de 1847, dos barcos de la Armada británica, el HMS Erebus y el HMS Terror, bajo el mando de sir John Franklin, van a la búsqueda del paso del Noroeste. En las cercanías de la isla del Rey Guillermo quedan atrapados en el hielo del Ártico.Las condiciones de supervivencia son extremas con temperaturas que superan los cincuenta grados bajo cero, provisiones de comida escasas, el deterioro de los barcos o la llegada de enfermedades. La extraña presencia de una criatura bestial y misteriosa hace que los hombres crean que se enfrentan a fuerzas sobrenaturales. El motín o el canibalismo planeean sobre los supervivientes.1",
    "img" : "https://www.libreriadesnivel.com/static/img/9788492429110_g.jpg",
    "price" : 3200,
    "stock": 1,
    "genre": "Terror",
    "available" : true,
    "writer" : "John Green",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0006',
    "name" : "El Exorcista",
    "review" : "El exorcista es una novela de terror escrita por William Peter Blatty y publicada en 1971. Se basa en un exorcismo efectuado en 1949, y del que Blatty oyó hablar en 1950, cuando recibía clases en la Universidad de Georgetown, un centro dirigido por sacerdotes jesuitas. ",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/81xddCQyGyL.__BG0,0,0,0_FMpng_AC_UL600_SR381,600_.jpg",
    "price" : 2000,
    "stock": 0,
    "genre": "Terror",
    "available" : false,
    "writer" : "William Peter Beatty",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0007',
    "name" : "Cabal",
    "review" : "Aaron Boone, el protagonista de la historia, sufre de una enfermedad mental, de la cual está siendo tratado por su psiquiatra, Decker. Para su desgracia, Boone es informado por Decker durante una sesión que él es el responsable del asesinato y mutilación de once personas, crímenes que han aterrorizado a la ciudadanía. Antes de perder toda esperanza, Boone comienza a pensar que la salvación se encuentra en un lugar llamado Midian, un lugar en el cual los monstruos pueden tener su santuario. Rápidamente se lanza a la búsqueda de Midian.Boone finalmente descubre que Midian es una laberíntica ciudad que se extiende kilómetros bajo un cementerio. Allí conocerá a las criaturas que lo pueblan. Lori, su novia, es incapaz de creer que Boone sea el autor de los crímenes y se lanza en su búsqueda, sin saber a ciencia cierta si Boone está vivo o no. Por su parte, Decker también desea hallarlo, pero con intenciones totalmente distintas. ",
    "img" : "https://www.minceraft.cl/media/k2/items/cache/e491c5d27469c8fba6ea9c1cbaaf20fe_M.jpg",
    "price" : 1800,
    "stock": 0,
    "genre": "Terror",
    "available" : false,
    "writer" : "Clive Barker",
    "top": false,
    "offers":false,
    "news":false,
  },
  { "id" : 'TE0008',
    "name" : "El Traje del Muerto",
    "review" : "Miles vive su vida sin emoción alguna, un día decide mudarse a Culver Creek, un internado fuera de lo común, donde disfrutará por primera vez de la libertad al conocer a Alaska Young, una chica preciosa, descarada, fascinante y autodestructiva, que de alguna manera arrastrará a Miles a su mundo.",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/51BvWPaC1qL._SX331_BO1,204,203,200_.jpg",
    "price" : 2200,
    "stock": 12,
    "genre": "Terror",
    "available" : false,
    "writer" : "Joe Hill",
    "top": false,
    "offers":false,
    "news":false,

  },];


