

const books = [{
    "name" : "1984",
    "review" : "En 1984, Londres está controlada por un gobieno totalitario. El Gran Hermano lo vigila absolutamente todo. La mano ejecutora, la Policía del Pensamiento, controla cada aspecto de la vida de los ciudadanos. Un hombre llamado Winston Smith, trabajador del Ministerio de la Verdad, intentará rebelarse contra el régimen opresor..",
    "img" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCjgIkmqNgIc1hZTa-QHt44TC22adESl8ZvQ&usqp=CAU",
    "price" : 350,
    "stock": 12,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "George Orwell",
  },{
    "name" : "Estudio en Escarlata",
    "review" : "Poco podía imaginar el Dr. John Watson que compartir piso en Londres iba a ser más emocionante y arriesgado que combatir en Afganistán. ¿El responsable? Su compañero de piso, Sherlock Holmes, cuyas dotes deductivas y personalidad fascinan a Watson.Estudio en escarlata es el trepidante comienzo de la andadura en común de los célebres inquilinos del 221B de Baker Street.",
    "img" : "https://grupoclaridad.com/wp-content/uploads/2018/04/estudio-escarlata-29101.jpg",
    "price" : 400,
    "stock": 5,
    "genre": "Policial",
    "available" : true,
    "writer" : "Edgar Allan Poe",

    
  },
  {
    "name" : "Harry Potter y La Orden del Fenix",
    "review" : " El Ministerio de Magia niega que Voldemort haya regresado y ha iniciado una campaña de desprestigio contra Harry y Dumbledore, para lo cual ha asignado a la horrible profesora Dolores Umbridge la tarea de vigilar todos sus movimientos. Así pues, además de sentirse solo e incomprendido, Harry sospecha que Voldemort puede adivinar sus pensamientos, e intuye que el temible mago trata de apoderarse de un objeto secreto que le permitiría recuperar su poder destructivo..",
    "img" : "https://catalogue.immateriel.fr/resources/2f/16/1c0e31e4be76f8dfbbba5cb6905f78b92bb0226e1dc51affd18947e3e185.jpg",
    "price" : 800,
    "stock": 0,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "J.K. Rowling",
  },
  {
    "name" : "Las venas abiertas de America Latina",
    "review" : "Las venas abiertas de América Latina” es un libro escrito por Eduardo Galeano. Aquí nos revela la realidad histórica de nuestra América, y nos proporciona una perspectiva acerca del contexto político específicamente de América, donde el lector puede hacer comparaciones pertinentes con respecto a la cultura de Estados Unidos y la de América Latina.",
    "img" : "https://images-na.ssl-images-amazon.com/images/I/41E6BToW6CL._SX319_BO1,204,203,200_.jpg",
    "price" : 950,
    "stock": 4,
    "genre": "Historia",
    "available" : false,
    "writer" : "Eduardo Galeano",
  },
  {
    "name" : "Harry potter y la camara secreta",
    "review" : "Mientras Harry espera impaciente en casa de sus insoportables tíos el inicio del segundo curso del Colegio Hogwarts de Magia y Hechicería, un elfo aparece en su habitación y le advierte de que una amenaza mortal se cierne sobre la escuela. Harry no se lo piensa dos veces y, acompañado de Ron, se dirige a Hogwarts en un coche volador. Pero, ¿puede un aprendiz de mago defender la escuela de los malvados que pretenden destruirla? Sin saber que alguien ha abierto la Cámara de los Secretos, dejando escapar una serie de monstruos peligrosos, Harry y sus amigos Ron y Hermione tendrán que enfrentarse con arañas gigantes, serpientes encantadas, fantasmas enfurecidos y, sobre todo, con la mismísima reencarnación de su más temible adversario.",
    "img" : "https://contentv2.tap-commerce.com/cover/large/9789878000114_1.jpg?id_com=1113",
    "price" : 1500,
    "stock": 0,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "Edgar Allan Poe",

    
  },
  {
    "name" : "El cuarto mono",
    "review" : "El detective de la policía de Chicago Sam Porter investiga el caso de un hombre atropellado, pues los indicios en la escena del crimen apuntan a que se trata de El Cuarto Mono, un asesino en serie que ha estado aterrorizando la ciudad. Su modus operandi consistía en enviar tres cajas blancas a los padres de las víctimas que secuestra y mata: una primera con una oreja, una segunda con los dos ojos, y otra con la lengua; y finalmente dejar abandonado el cuerpo sin vida en algún lugar.El hombre atropellado llevaba una de esas cajas blancas. Se inicia así una frenética carrera contrarreloj para averiguar dónde se encuentra encerrada la próxima víctima.",
    "img" : "https://planetadelibrosar5.cdnstatics.com/usuaris/libros/fotos/304/m_prensa/303713_el-cuarto-mono_9788423353941_3d.png",
    "price" : 1200,
    "stock": 7,
    "genre": "Policial",
    "available" : true,
    "writer" : "J.D Barker",

    
  },
  {
    "name" : "Fahrenheit 451",
    "review" : "Fahrenheit 451' no es un libro fácil de leer, porque nos lleva a una situación que no tiene nada de fantástica. Estamos en un país donde no se puede leer. De hecho, el trabajo del bombero Montag, el protagonista, no es apagar incendios, sino provocarlos. Se dedica a quemar libros para evitar que la población piense y se la pueda manipular;",
    "img" : "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/elle-fahrenheit451-1582115505.jpg?crop=1xw:1xh;center,top&resize=480:*",
    "price" : 850,
    "stock": 16,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "Ray Bradbury",

    
  },
  {
    "name" : "El señor de las moscas",
    "review" : "Una obra cuya calidad tiene tanto defensores como detractores, y que fue adaptada recientemente como serie por Netflix bajo el título 'The Society'. William Golding, premio Nobel de Literatura en 1983 nos lleva hasta la próxima guerra mundial, cuando el avión en el que viajan un grupo de jóvenes se estrella en una isla desconocida. Sin adultos que les supervisen, todo comienza siendo una fiesta, porque pueden hacer lo que quieran. Con lo que no contaban es con la dificultad y la tragedia de establecer una sociedad..",
    "img" : "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/elle-elsen-ordelasmoscas-1582115504.jpg?crop=1xw:1xh;center,top&resize=480:*",
    "price" : 1400,
    "stock": 2,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "William Golding",
  },
  {
    "name" : "El cuento de la criada",
    "review" : "La serie de HBO inspirada en él ha dado alas a este cuento escrito a mediados de los 90 por Margaret Atwood, una historia inquietante, oscura y angustiosa que nos sitúa en la república de Gilead, donde Defred es una más de tantas mujeres que han perdido todos sus derechos y que solo sirven para una cosa: procrear. Atwood nos sumerge en un mundo asfixiante que nos hace reflexionar si podría ser nuestro propio planeta.",
    "img" : "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cuentocriada-1524221026.jpg?crop=1xw:1xh;center,top&resize=480:*",
    "price" : 1700,
    "stock": 0,
    "genre": "Ciencia Ficcion",
    "available" : false,
    "writer" : "Margaret Atwood",
  },
  {
    "name" : "La buena suerte",
    "review" : "Rosa Montero regresa para conquistar nuevamente al lector con una novela que captura y engancha a través de Pablo, de Raluca, de todos los vecinos de Pozonegro que guardan un secreto. A través de Pablo viviremos con él la caída y las consecuencias de un terremoto emocional, el suyo propio, pero también cómo uno puede enfrentarse al mismo y descubrirse, redescubrirse y ver hacia dónde puede llevarle.",
    "img" : "https://espaciolibros.com//wp-content/uploads/2020/08/libros-recomendados-2020-rosa-montero-la-buena-suerte.jpg",
    "price" : 700,
    "stock": 10,
    "genre": "Drama",
    "available" : true,
    "writer" : "Rosa Montero",
  },
  {
    "name" : "Cien años de soledad",
    "review" : "«Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.» Con estas palabras empieza una novela legendaria, una de las aventuras literarias más fascinantes del siglo XX. La familia Buendía-Iguarán, con sus milagros, fantasías, obsesiones, tragedias, incestos, adulterios, rebeldías, descubrimientos y condenas, representa al mismo tiempo el mito y la historia, la tragedia y el amor del mundo entero. «El Quijote de nuestro tiempo.» Pablo Neruda",
    "img" : "https://2.bp.blogspot.com/-BbVKIZIg2pA/UO5o9vqB7TI/AAAAAAAAACE/OPrwTtiHfAs/s1600/cienanos.gif",
    "price" : 700,
    "stock": 10,
    "genre": "Drama",
    "available" : true,
    "writer" : "Gabriel Garcia Marquez",
  },
  {
    "name" : "El señor de los anillos",
    "review" : "El Señor de los Anillos es una obra ambientada en la Tercera Edad de La Tierra Media, mundo inventado por JRR Tolkien. Narra una gran aventura: el viaje emprendido por 9 compañeros para destruir un Anillo lleno de poder maléfico. Su argumento es complejo y se narra con la participación de varios protagonistas que se mueven en varios hilos narrativos. Es una obra coral en la que destacan unos pocos protagonistas (Frodo, Sam, Gandalf y Aragorn).",
    "img" : "https://2.bp.blogspot.com/_x2vBZUXDzVk/S-RhI8ugR-I/AAAAAAAAAls/8dTO6VD_2rM/s1600/imagen_biblioesdla_1.jpg",
    "price" : 3700,
    "stock": 10,
    "genre": "Fantastico",
    "available" : true,
    "writer" : "J.R.R Tolkien",
  },
  {
    "name" : "Un mundo feliz",
    "review" : "Un mundo feliz es un clásico de la literatura de este siglo. Con ironía mordiente, el genial autor inglés plasma una sombría metáfora sobre el futuro, muchas de cuyas previsiones se han materializado, acelerada e inquietantemente, en los últimos años. La novela describe un mundo en el que finalmente se han cumplido los peor es vaticinios: triunfan los dioses del consumo y la comodidad, y el orbe se organiza en diez zonas en apariencia seguras y estables. Sin embargo, este mundo ha sacrificado valores humanos esenciales, y sus habitantes son procreados in vitro a imagen y semejanza de una cadena de montaje…",
    "img" : "https://i.pinimg.com/originals/01/db/f0/01dbf0de11087b535d2c660481dd4135.jpg",
    "price" : 1200,
    "stock": 8,
    "genre": "Ciencia Ficcion",
    "available" : true,
    "writer" : "Aldous Huxley",
  },
  {
    "name" : "Manuel Belgrano:El hombre del Bicentenario",
    "review" : "En esta nueva obra, Felipe Pigna aborda el estudio integral de la agitada vida de Belgrano, tanto en lo público como en lo privado y familiar. Además de sus facetas más conocidas como protagonista de la Revolución de Mayo y general de la Independencia, aparecen con gran relevancia en estas páginas los aspectos menos divulgados: su ideario progresista y las incontables batallas que libró para llevarlo a la práctica.",
    "img" : "https://www.planetadelibros.com.ar/usuaris/libros/fotos/216/m_libros/portada_manuel-belgrano_felipe-pigna_201604261432.jpg",
    "price" : 2000,
    "stock": 12,
    "genre": "Historia",
    "available" : true,
    "writer" : "Felipe Pigna",
  },
  {
    "name" : "Mujeres insolentes de la historia",
    "review" : "Hicieron historia. Igual que muchos hombres.Pero a ellas se les mezquinó la memoria de sus actos. Tardaron en aparecer en los libros, en las revistas, en los manuales de la escuela, en las conmemoraciones. Fueron mujeres valientes, arriesgadas, talentosas, capaces de ir contra lo que su época decía que había que hacer. Estuvieron a la altura de una historia que luego las arrumbó en un costado, fueron las “insolentes” en ese mundo.En este libro, Felipe Pigna nos cuenta la vida de algunas mujeres latinoamericanas que se sublevaron para hacer lo que querían.",
    "img" : "https://planetadelibrosar2.cdnstatics.com/usuaris/libros/fotos/272/m_libros/portada___201804092101.jpg",
    "price" : 1800,
    "stock": 8,
    "genre": "Historia",
    "available" : true,
    "writer" : "Felipe Pigna",
  },
  {
    "name" : "El muñeco de nieve",
    "review" : "Las aventuras del policía noruego Harry Hole gozan hoy de un amplio público. Esta es una de las primeras novelas de Jo Nesbo, pero no nos equivocaríamos al valorarla como la más perfecta y contenida (en otras el protagonista cae en un desbarre más peliculero). En estas páginas Hole se enfrenta al caso de un psicópata que va haciendo desaparecer mujeres y dejando un muñequito de nieve con bufanda como señal… 'a priori'. Pero también trata otros asuntos como la paternidad. Una novela trepidante que fue llevada al cine, más mal que bien. No le hacía falta. Tiene fans por todo el planeta. Hasta Patti Smith, ávida lectora, ha declarado alimentarse con fruición de Nesbo.",
    "img" : "https://www.ecestaticos.com/image/clipping/fdef4d1bb993fbbd6ec833c84e57e9cb/el-muneco-de-nieve.jpg",
    "price" : 1400,
    "stock": 8,
    "genre": "Policial",
    "available" : true,
    "writer" : "Jo Nesbo",
  },
  {
    "name" : "Crimen y castigo",
    "review" : "Crimen y castigo, una novela de asesinato y angustia, en la que una de las características más determinantes es la profundización de la psicología de los personajes. Esta dedicación a la descripción y los diálogos internos acerca la novela a un ensayo sobre la psicología humana.",
    "img" : "https://cdn-0.infolibros.org/wp-content/uploads/2020/06/11-Crimen-y-castigo-Fiódor-Dostoievski.jpg?ezimgfmt=rs:292x456/rscb32/ng:webp/ngcb32",
    "price" : 3400,
    "stock": 11,
    "genre": "Policial",
    "available" : true,
    "writer" : "Fiódor Dostoievski",
  },
  {
    "name" : "Don Quijote de la Mancha",
    "review" : "Crimen y castigo, una novela de asesinato y angustia, en la que una de las características más determinantes es la profundización de la psicología de los personajes. Esta dedicación a la descripción y los diálogos internos acerca la novela a un ensayo sobre la psicología humana.",
    "img" : "https://cdn-0.infolibros.org/wp-content/uploads/2020/06/18-Don-Quijote-de-la-Mancha-Miguel-de-Cervantes.png?ezimgfmt=rs:0x0/rscb32/ng:webp/ngcb32",
    "price" : 2500,
    "stock": 2,
    "genre": "Historia",
    "available" : true,
    "writer" : "Miguel de Cervantes",
  },
  {
    "name" : "Moby Dick",
    "review" : "Crimen y castigo, una novela de asesinato y angustia, en la que una de las características más determinantes es la profundización de la psicología de los personajes. Esta dedicación a la descripción y los diálogos internos acerca la novela a un ensayo sobre la psicología humana.",
    "img" : "https://cdn-0.infolibros.org/wp-content/uploads/2020/06/76-Moby-Dick-Herman-Melville.jpg?ezimgfmt=rs:0x0/rscb32/ng:webp/ngcb32",
    "price" : 2500,
    "stock": 0,
    "genre": "Fantastico",
    "available" : false,
    "writer" : "Herman Melville",
  },
  {
    "name" : "Cianuro Espumoso",
    "review" : "En el reservado de un selecto restaurante, seis personas se reúnen alrededor de una mesa preparada para siete comensales. Ante el asiento vacío hay un ramillete de romero en memoria de Rosemary Burton, fallecida en aquel mismo escenario un año atrés después de haber ingerido cianuro disuelto en su copa. En aquel momento todo el mundo pensó que se trataba de un suicidio. Hoy ya no. Ahora existen sospechas fundadas de que en realidad Rosemary fue asesinada. Y lo que en un principio parecía una cena organizada en homenaje a la difunta se va a convertir en otra cosa muy distinta. Una peligrosa conmemoración que puede volver a acabar en tragedia cuando, al alzar la copa para brindar en recuerdo de la fallecida, uno de los comensales se desploma en su silla.",
    "img" : "https://planetadelibrosar4.cdnstatics.com/usuaris/libros/fotos/204/m_libros/portada_cianuro-espumoso_agatha-christie_201506292037.jpg",
    "price" : 4500,
    "stock": 22,
    "genre": "Policial",
    "available" : false,
    "writer" : "Agatha Christie",
  },

  
  ];



